/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.CardLayout;

/**
 *
 * @author H_Kofi
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        FormJPanel newFormJPanel=new FormJPanel(BottomjPanel);
        this.BottomjPanel.add(newFormJPanel);
        CardLayout Layout=(CardLayout)this.BottomjPanel.getLayout();
        Layout.next(BottomjPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        TopjPanel = new javax.swing.JPanel();
        FormjButton = new javax.swing.JButton();
        ViewjButton = new javax.swing.JButton();
        BottomjPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        FormjButton.setText("Form");
        FormjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormjButtonActionPerformed(evt);
            }
        });

        ViewjButton.setText("View");
        ViewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopjPanelLayout = new javax.swing.GroupLayout(TopjPanel);
        TopjPanel.setLayout(TopjPanelLayout);
        TopjPanelLayout.setHorizontalGroup(
            TopjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopjPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(FormjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(ViewjButton)
                .addGap(104, 104, 104))
        );
        TopjPanelLayout.setVerticalGroup(
            TopjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopjPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(TopjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FormjButton)
                    .addComponent(ViewjButton))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(TopjPanel);

        BottomjPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(BottomjPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FormjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormjButtonActionPerformed
        // TODO add your handling code here:
        FormJPanel newFormJPanel=new FormJPanel(BottomjPanel);
        this.BottomjPanel.add(newFormJPanel);
        CardLayout Layout=(CardLayout)this.BottomjPanel.getLayout();
        Layout.next(BottomjPanel);
    }//GEN-LAST:event_FormjButtonActionPerformed

    private void ViewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewjButtonActionPerformed
        // TODO add your handling code here:
ViewJPanel newViewJPanel=new ViewJPanel();
this.BottomjPanel.add(newViewJPanel);
CardLayout layout=(CardLayout)this.BottomjPanel.getLayout();
layout.next(BottomjPanel);

    }//GEN-LAST:event_ViewjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomjPanel;
    private javax.swing.JButton FormjButton;
    private javax.swing.JPanel TopjPanel;
    private javax.swing.JButton ViewjButton;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
